/* EXAMPLE OF A DRILL DOWN FOR A SELECTED TEAM. HERE WE CHECKED THE W/L MATCH RECORD, SAW THAT SEA HAS A LOSING RECORD, AND DECIDED TO DELVE DEEPER INTO THEIR TEAM STATS. 
WE FIND OUT THAT SEA HAS A LOSING RECORD ON BREENBERGH HOTEL (4-12) AND INVESTIGATED THE MODE WITH THE MOST LOSSES (CDL CONTROL). WE THEN CHECK THE AVERAGED STATS PER SEA VERSUS THE AVG CDL STATS 
IN CERTAIN PLAYER CATEGORIES (KILLS, DEATHS, UNTRADED KILLS, ETC) TO DETERMINE IF THEIR TEAM PLAY IS OFF OR IF A PLAYER ON THER TEAM NEEDS INVESTIGATION FOR POOR PERFORMANCE. */


SELECT -----QUERY TO DISPLAY HOW MANY TIMES TEAM PLAYED A MAP
	T.ABV,
	M.MAP_NAME,
	COUNT(MM.MAP_ID)AS TIMES_PLAYED,
	COUNT(CASE WHEN MM.WINNING_TEAM_ID = T.TEAM_ID THEN MM.WINNING_TEAM_ID END) AS MAP_WINS,
	RANK () OVER (PARTITION BY T.ABV ORDER BY COUNT(MM.MAP_ID) DESC) AS RANKING
FROM MATCHMAPS MM
JOIN MAP M
	ON M.MAP_ID = MM.MAP_ID
JOIN TEAM T
	ON T.TEAM_ID IN (MM.WINNING_TEAM_ID, MM.LOSING_TEAM_ID)
WHERE T.ABV IN ('TX','TOR','SEA','NY','LAT')	

GROUP BY T.ABV,M.MAP_NAME;



SELECT  ----QUERY TO DETERMINE WHICH MAP/MAP MODE COMBINATIONS SEA IS LOSING THE MOST
	T.ABV,
	M.MAP_NAME,
	M.MAP_MODE,
	COUNT(CASE WHEN MM.WINNING_TEAM_ID = T.TEAM_ID THEN MM.WINNING_TEAM_ID END) AS MAP_WINS,
	COUNT(CASE WHEN MM.LOSING_TEAM_ID = T.TEAM_ID THEN MM.LOSING_TEAM_ID END) AS MAP_LOSSES
	
FROM 
	 MATCHMAPS MM
JOIN MAP M
	ON MM.MAP_ID = M.MAP_ID
JOIN TEAM T
	ON T.TEAM_ID IN (MM.WINNING_TEAM_ID,MM.LOSING_TEAM_ID)
WHERE T.ABV = 'SEA'

GROUP BY 1,2,3
ORDER BY 5 DESC;
/*"SEA"	"Breenbergh Hotel"	"CDL Control"	2	6
"SEA"	"Breenbergh Hotel"	"CDL Hardpoint"	2	4
"SEA"	"Al Bagra Fortress"	"CDL SnD"		0	3
"SEA"	"Embassy"	"CDL Hardpoint"			2	2*/


---THIS CTE WILL DISPLAY THE AVERAGE STATS FOR SEA DURING THEIR 6 CONTROL MAP LOSES ON HOTEL CONTROL VERSUS THE CDL AVERAGE 

WITH	LOSING_CONTROL_SCORES AS (
		
		SELECT
			T.ABV,
			MM.MATCH_MAP_ID,
			HOME_SCORE AS LOSING_CTRL_SCORES
		FROM MATCHMAPS MM
		JOIN TEAM T
			ON	T.TEAM_ID = MM.LOSING_TEAM_ID
		WHERE MM.LOSING_TEAM_ID = (SELECT TEAM_ID FROM TEAM WHERE ABV = 'SEA')
		AND MAP_ID IN (SELECT MAP_ID FROM MAP WHERE MAP_MODE = 'CDL Control')
		AND HOME_SCORE <> 3 /*OR AWAY_SCORE <> 250*/
		AND MAP_NAME = 'Breenbergh Hotel'
		
		UNION ALL
		
		SELECT
			T.ABV,
			MM.MATCH_MAP_ID,
			AWAY_SCORE AS LOSING_CTRL_SCORES
		FROM MATCHMAPS MM
		JOIN TEAM T
			ON	T.TEAM_ID = MM.LOSING_TEAM_ID
		WHERE MM.LOSING_TEAM_ID = (SELECT TEAM_ID FROM TEAM WHERE ABV = 'SEA')
		AND MAP_ID IN (SELECT MAP_ID FROM MAP WHERE MAP_MODE = 'CDL Control')
		AND AWAY_SCORE <> 3
		AND MAP_NAME = 'Breenbergh Hotel'),
		
		CDL_TEAM_AVG AS (
		
		SELECT

			AVG(MS.TOTAL_KILLS) AS CDL_AVG_TOTAL_KILLS,
			AVG(MS.UNTRADED_DEATHS) AS CDL_AVG_UNTRADED_DEATHS,
			AVG(MS.UNTRADED_KILLS) AS CDL_AVG_UNTRADED_KILLS,
			AVG(CONTROL_TIERS_CAPTURED) AS CDL_AVG_CTRL_SEGMENTS_CAPTURED,
			AVG(MS.DAMAGE_DEALT) AS CDL_AVG_DAMAGE_DEALT
		FROM MATCHSTATS MS 
		
		WHERE MS.PLAYER_ID NOT IN (SELECT PLAYER_ID FROM PLAYER P JOIN TEAM T ON T.TEAM_ID = P.TEAM_ID WHERE T.ABV = 'SEA')
		AND MS.MATCH_MAP_ID IN (SELECT MATCH_MAP_ID FROM MATCHMAPS MM JOIN MAP M ON M.MAP_ID = MM.MAP_ID WHERE M.MAP_MODE = 'CDL Control'))

		/*AVG_HP_LOSING_SCORE AS (*/
	
SELECT
	ABV,
	ROUND(AVG(LOSING_CTRL_SCORES),2) AS AVG_CTRL_SCORE,
	ROUND(AVG(MS.TOTAL_KILLS),2) AS AVG_TOTAL_KILLS,
	ROUND(CDL_AVG_TOTAL_KILLS,2) AS CDL_AVG_TOTAL_KILLS,
	ROUND(AVG(MS.UNTRADED_DEATHS),2) AS AVG_UNTRADED_DEATHS,
	ROUND(CDL_AVG_UNTRADED_DEATHS,2) AS CDL_AVG_UNTRADED_DEATHSS,
	ROUND(AVG(MS.UNTRADED_KILLS),2) AS AVG_UNTRADED_KILLS,
	ROUND(CDL_AVG_UNTRADED_KILLS,2) AS AVG_CDL_UNTRADED_KILLS,
	ROUND(AVG(CONTROL_TIERS_CAPTURED),2) AS AVG_CTRL_SEGMENTS_CAPTURED,
	ROUND(CDL_AVG_CTRL_SEGMENTS_CAPTURED,2) AS AVG_CDL_CTRL_SEGMENTS_CAPTURED,
	ROUND(AVG(MS.DAMAGE_DEALT),2) AS AVG_DAMAGE_DEALT,
	ROUND(CDL_AVG_DAMAGE_DEALT,2) AS AVG_CDL_DAMAGE_DEALT

FROM CDL_TEAM_AVG, LOSING_CONTROL_SCORES LCS 
JOIN MATCHSTATS MS 
	ON LCS.MATCH_MAP_ID = MS.MATCH_MAP_ID
WHERE MS.PLAYER_ID IN (SELECT PLAYER_ID FROM PLAYER P JOIN TEAM T ON T.TEAM_ID = P.TEAM_ID WHERE T.ABV = 'SEA')
	AND MS.MATCH_MAP_ID IN (SELECT MATCH_MAP_ID FROM MATCHMAPS MM JOIN MAP M ON M.MAP_ID = MM.MAP_ID WHERE M.MAP_MODE = 'CDL Control')
	GROUP BY 1 ,CDL_AVG_TOTAL_KILLS,6,8,10,12 
		

	
