-------------------------------------------------------------------------------
---------------------ANALYSIS ON TEAM LEVEL------------------------------------
-------------------------------------------------------------------------------


SELECT ----QUERY FOR WIN/LOSS RECORD FOR TEAMS WITH MORE THAN 5 MATCHES.
	TEAM.ABV,
	COUNT(CASE WHEN MATCH.WINNING_TEAM_ID = TEAM.TEAM_ID THEN MATCH.LOSING_TEAM_ID END) AS WINS,  
	COUNT(CASE WHEN MATCH.LOSING_TEAM_ID = TEAM.TEAM_ID THEN MATCH.LOSING_TEAM_ID END) AS LOSSES
FROM MATCH
JOIN TEAM ON TEAM.TEAM_ID IN (MATCH.HOME_TEAM_ID, MATCH.AWAY_TEAM_ID)
GROUP BY TEAM.ABV
HAVING COUNT(CASE WHEN MATCH.WINNING_TEAM_ID = TEAM.TEAM_ID THEN 1 END) + COUNT(CASE WHEN MATCH.LOSING_TEAM_ID = TEAM.TEAM_ID THEN 1 END) >= 5 
ORDER BY 1 DESC;

/*
"abv"	"wins"	"losses"
"TX"	7	2
"TOR"	4	1
"SEA"	2	7
"NY"	5	4
"LAT"	3	6 */ 


SELECT ----QUERY TO DISPLAY MAP MODES WON PER TEAM
	T.ABV,
	--MAP.MAP_NAME,
	MAP.MAP_MODE,
	SUM(CASE WHEN MM.WINNING_TEAM_ID = T.TEAM_ID THEN 1 ELSE 0 END) AS MAP_WINS,  
	SUM(CASE WHEN MM.LOSING_TEAM_ID = T.TEAM_ID THEN 1 ELSE 0 END) AS MAP_LOSSES,
	ROUND(CAST(SUM(CASE WHEN MM.WINNING_TEAM_ID = T.TEAM_ID THEN 1 ELSE 0 END) AS NUMERIC)  /   (SUM(CASE WHEN MM.WINNING_TEAM_ID = T.TEAM_ID THEN 1 ELSE 0 END) + SUM(CASE WHEN MM.LOSING_TEAM_ID = T.TEAM_ID THEN 1 ELSE 0 END)) * 100) || ' %'
	AS WIN_RATIO 
FROM MATCHMAPS MM
JOIN TEAM T
	ON T.TEAM_ID IN (MM.WINNING_TEAM_ID, MM.LOSING_TEAM_ID)
JOIN MAP 
	ON MM.MAP_ID = MAP.MAP_ID
WHERE T.ABV IN ('TX','TOR','SEA','NY','LAT')	
GROUP BY 1,2
ORDER BY 1;	


SELECT -----QUERY TO DISPLAY HOW MANY TIMES TEAM PLAYED A MAP
	T.ABV,
	M.MAP_NAME,
	COUNT(MM.MAP_ID)AS TIMES_PLAYED,
	RANK () OVER (PARTITION BY T.ABV ORDER BY COUNT(MM.MAP_ID) DESC) AS RANKING
FROM MATCHMAPS MM
JOIN MAP M
	ON M.MAP_ID = MM.MAP_ID
JOIN TEAM T
	ON T.TEAM_ID IN (MM.WINNING_TEAM_ID, MM.LOSING_TEAM_ID)
WHERE T.ABV IN ('TX','TOR','SEA','NY','LAT')	

GROUP BY T.ABV,M.MAP_NAME;


-------------------------------------------------------------------------------
---------------------ANALYSIS ON PLAYER LEVEL----------------------------------
-------------------------------------------------------------------------------

SELECT --Query to show avg(K/D ratio) chronologically by match_play_time 
	P.ALIAS,
	TO_TIMESTAMP(MATCH.MATCH_PLAY_TIME) AS TIME_PLAYED,
	ROUND(AVG(CAST(MS.TOTAL_KILLS AS NUMERIC)/ (MS.TOTAL_DEATHS)) OVER(PARTITION BY P.ALIAS ORDER BY TO_TIMESTAMP(MATCH.MATCH_PLAY_TIME) ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW ),2)AS UPDATING_K_D
FROM MATCHSTATS MS
JOIN MATCHMAPS MM
	ON MS.MATCH_MAP_ID = MM.MATCH_MAP_ID	
JOIN PLAYER	P
	ON P.PLAYER_ID = MS.PLAYER_ID
JOIN MATCH 
	ON MATCH.MATCH_ID = MM.MATCH_ID
JOIN PLAYERS_CHOSEN PC
	ON PC.ALIAS = P.ALIAS
JOIN MAP 
	ON MAP.MAP_ID = MM.MAP_ID
WHERE P.ALIAS = PC.ALIAS
AND (MS.TOTAL_KILLS > 0 AND MS.TOTAL_DEATHS > 0)
AND MAP.MAP_MODE LIKE '%SnD'
GROUP BY P.ALIAS, TO_TIMESTAMP(MATCH.MATCH_PLAY_TIME), MS.TOTAL_KILLS, MS.TOTAL_DEATHS
ORDER BY 1,2;











Select count(*) 
from matchstats ms
Join player p
	on p.player_id = ms.player_id
Where lower(alias) = 'standy';

Select count(*) 
from matchstats ms
Join player p
	on p.player_id = ms.player_id
Where lower(alias) = 'huke';

